services:
  hackitsso:
    build: .
    ports:
      - "7411:7411"
    environment:
      - DATABASE_SERVICE_URL=${DATABASE_SERVICE_URL:-http://localhost:8001}
      - DATABASE_SERVICE_SECRET=${DATABASE_SERVICE_SECRET}
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379/0}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
      - MAGIC_LINK_TOKEN_EXPIRE_MINUTES=${MAGIC_LINK_TOKEN_EXPIRE_MINUTES:-15}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_FROM=${MAIL_FROM:-noreply@hackit.tw}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-HackIt SSO}
      - MAIL_STARTTLS=${MAIL_STARTTLS:-true}
      - MAIL_SSL_TLS=${MAIL_SSL_TLS:-false}
      - USE_CREDENTIALS=${USE_CREDENTIALS:-true}
      - VALIDATE_CERTS=${VALIDATE_CERTS:-true}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY:-}
      - TURNSTILE_SITE_KEY=${TURNSTILE_SITE_KEY:-}
      - SSO_DOMAIN=${SSO_DOMAIN:-sso.hackit.tw}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS:-hackit.tw,*.hackit.tw}
      - OIDC_ISSUER=${OIDC_ISSUER:-https://sso.hackit.tw}
      - OIDC_KEY_ID=${OIDC_KEY_ID:-hackit-sso-key-1}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - OIDC_ADMIN_KEY=${OIDC_ADMIN_KEY}
      - OIDC_CLIENTS=${OIDC_CLIENTS}
    restart: unless-stopped

networks:
  coolify:
    external: true